<a href="https://colab.research.google.com/github/VivianeSouza923/Python-Study/blob/main/tabelas_frequencia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('/content/Pesquisa Nacional por Amostra de Domicílios.csv - Pesquisa Nacional por Amostra de Domicílios.csv.csv')
df

       UF  Sexo  Idade  Cor  Anos de Estudo   Renda         Altura
0      11     0     23    8              12   800.0  1.603.807.616
1      11     1     23    2              12  1150.0  1.739.789.827
2      11     1     35    8              15   880.0  1.760.443.822
3      11     0     46    2               6  3500.0  1.783.157.945
4      11     1     47    8               9   150.0  1.690.630.954
...    ..   ...    ...  ...             ...     ...            ...
33178  31     0     60    4              12  8000.0  1.649.400.782
33179  31     0     33    8              15  2300.0  1.693.094.939
33180  31     1     31    8              12  2000.0  1.849.360.141
33181  31     1     52    2               9  4000.0  1.785.048.175
33182  31     0     36    8               1     NaN            NaN

[33183 rows x 7 columns]

In [4]:

# para conhecer a base:
# imprime um resumo conciso do dataframe (a base)
# esse método imprime informações sobre o dataframe, incluíndo dtype e colunas do index, valores não nulos e uso de memória.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33183 entries, 0 to 33182
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   UF              33183 non-null  int64
 1   Sexo            33183 non-null  int64
 2   Idade           33183 non-null  int64
 3   Cor             33183 non-null  int64
 4   Anos de Estudo  33183 non-null  int64
 5   Renda           33182 non-null  float64
 6   Altura          33182 non-null  object
dtypes: float64(1), int64(5), object(1)
memory usage: 1.8+ MB

In [5]:
# trocando os códigos pelos significados:
# acessando a coluna sexo do dataframe, eu vou alterar os valores 0 e 1 para masculino e feminino, respectivamente. O inplace=True serve para especificar que a modificação será feita no próprio dataframe, em vez de retornar uma cópia dele com a modificação.
df['Sexo'].replace({0:'Masculino', 1: 'Feminino'}, inplace=True)
df

       UF       Sexo  Idade  Cor  Anos de Estudo   Renda         Altura
0      11  Masculino     23    8              12   800.0  1.603.807.616
1      11   Feminino     23    2              12  1150.0  1.739.789.827
2      11   Feminino     35    8              15   880.0  1.760.443.822
3      11  Masculino     46    2               6  3500.0  1.783.157.945
4      11   Feminino     47    8               9   150.0  1.690.630.954
...    ..        ...    ...  ...             ...     ...            ...
33178  31  Masculino     60    4              12  8000.0  1.649.400.782
33179  31  Masculino     33    8              15  2300.0  1.693.094.939
33180  31   Feminino     31    8              12  2000.0  1.849.360.141
33181  31   Feminino     52    2               9  4000.0  1.785.048.175
33182  31  Masculino     36    8               1     NaN            NaN

[33183 rows x 7 columns]

In [6]:
df['UF'].replace({
    11:'Rondônia',
    12:'Acre',
    13:'Amazonas',
    14:'Roraima',
    15:'Pará',
    16:'Amapá',
    17:'Tocatins',
    21:'Maranhão',
    22:'Piauí',
    23:'Ceará',
    24:'Rio Grande do Norte',
    25:'Paraíba',
    26:'Pernambuco',
    27:'Alagoas',
    28:'Sergipe',
    29:'Bahia',
    31:'Minas Gerais',
    32:'Espírito Santo',
    33:'Rio de Janeiro',
    35:'São Paulo',
    41:'Paraná',
    42:'Santa Catarina',
    43:'Rio Grande do Sul',
    50:'Mato Grosso do Sul',
    51:'Mato Grosso',
    52:'Goiás',
    53:'Distrito Federal'

}, inplace=True)

df

,UF,Sexo,Idade,Cor,Anos de Estudo,Renda,Altura
0,Rondônia,Masculino,23,8,12,800.0,1.603.807.616
1,Rondônia,Feminino,23,2,12,1150.0,1.739.789.827
2,Rondônia,Feminino,35,8,15,880.0,1.760.443.822
3,Rondônia,Masculino,46,2,6,3500.0,1.783.157.945
4,Rondônia,Feminino,47,8,9,150.0,1.690.630.954
...,...,...,...,...,...,...,...
33178,Minas Gerais,Masculino,60,4,12,8000.0,1.649.400.782
33179,Minas Gerais,Masculino,33,8,15,2300.0,1.693.094.939
33180,Minas Gerais,Feminino,31,8,12,2000.0,1.849.360.141
33181,Minas Gerais,Feminino,52,2,9,4000.0,1.785.048.175
33182,Minas Gerais,Masculino,36,8,1,NaN,NaN

In [7]:
anos_de_estudo = {
    1:'Sem instrução e menos de 1 ano',
    2:'1 ano',
    3:'2 anos',
    4:'3 anos',
    5:'4 anos',
    6:'5 anos',
    7:'6 anos',
    8:'7 anos',
    9:'8 anos',
    10:'9 anos',
    11:'10 anos',
    12:'11 anos',
    13:'12 anos',
    14:'13 anos',
    15:'14 anos',
    16:'15 anos ou mais',
    17:'Não determinados',

}

df['Anos de Estudo'].replace(anos_de_estudo, inplace=True)
df

,UF,Sexo,Idade,Cor,Anos de Estudo,Renda,Altura
0,Rondônia,Masculino,23,8,11 anos,800.0,1.603.807.616
1,Rondônia,Feminino,23,2,11 anos,1150.0,1.739.789.827
2,Rondônia,Feminino,35,8,14 anos,880.0,1.760.443.822
3,Rondônia,Masculino,46,2,5 anos,3500.0,1.783.157.945
4,Rondônia,Feminino,47,8,8 anos,150.0,1.690.630.954
...,...,...,...,...,...,...,...
33178,Minas Gerais,Masculino,60,4,11 anos,8000.0,1.649.400.782
33179,Minas Gerais,Masculino,33,8,14 anos,2300.0,1.693.094.939
33180,Minas Gerais,Feminino,31,8,11 anos,2000.0,1.849.360.141
33181,Minas Gerais,Feminino,52,2,8 anos,4000.0,1.785.048.175
33182,Minas Gerais,Masculino,36,8,Sem instrução e menos de 1 ano,NaN,NaN

In [8]:

cor = {
    0:'Indígena',
    2:'Branca',
    4:'Preta',
    6:'Amarela',
    8:'Parda',
    9:'Sem declaração'
}

df['Cor'].replace(cor, inplace=True)
df

,UF,Sexo,Idade,Cor,Anos de Estudo,Renda,Altura
0,Rondônia,Masculino,23,Parda,11 anos,800.0,1.603.807.616
1,Rondônia,Feminino,23,Branca,11 anos,1150.0,1.739.789.827
2,Rondônia,Feminino,35,Parda,14 anos,880.0,1.760.443.822
3,Rondônia,Masculino,46,Branca,5 anos,3500.0,1.783.157.945
4,Rondônia,Feminino,47,Parda,8 anos,150.0,1.690.630.954
...,...,...,...,...,...,...,...
33178,Minas Gerais,Masculino,60,Preta,11 anos,8000.0,1.649.400.782
33179,Minas Gerais,Masculino,33,Parda,14 anos,2300.0,1.693.094.939
33180,Minas Gerais,Feminino,31,Parda,11 anos,2000.0,1.849.360.141
33181,Minas Gerais,Feminino,52,Branca,8 anos,4000.0,1.785.048.175
33182,Minas Gerais,Masculino,36,Parda,Sem instrução e menos de 1 ano,NaN,NaN

In [9]:
# item a) tabela de frequência para variáveis qualitativas:

# * Tabela de Frequência para a variável UF *

tabela_frequencia_UF = df['UF'].value_counts().reset_index()
tabela_frequencia_UF.columns = ['UF', 'Frequencia']

print(tabela_frequencia_UF)

                     UF  Frequencia
0                 Bahia        5717
1                  Pará        4449
2            Pernambuco        3820
3                 Ceará        3359
4              Amazonas        2206
5              Maranhão        1787
6              Rondônia        1537
7          Minas Gerais        1365
8              Tocatins        1306
9               Sergipe        1287
10              Paraíba        1274
11                Piauí        1211
12  Rio Grande do Norte         973
13                 Acre         937
14              Alagoas         903
15              Roraima         540
16                Amapá         512

In [10]:
# * Tabela de Frequência para a variável Sexo *

tabela_frequencia_sexo = df['Sexo'].value_counts().reset_index()
tabela_frequencia_sexo.columns = ['Sexo', 'Frequencia']

print(tabela_frequencia_sexo)

        Sexo  Frequencia
0  Masculino       22847
1   Feminino       10336

In [11]:
# * Tabela de Frequência para a variável cor *

tabela_frequencia_cor = df['Cor'].value_counts().reset_index()
tabela_frequencia_cor.columns = ['Cor', 'Frequencia']

print(tabela_frequencia_cor)

        Cor  Frequencia
0     Parda       20753
1    Branca        7814
2     Preta        4301
3  Indígena         238
4   Amarela          77

In [12]:
# * Tabela de Frequência para a variável Anos de estudo *

tabela_frequencia_Anos_de_estudo = df['Anos de Estudo'].value_counts().reset_index()
tabela_frequencia_Anos_de_estudo.columns = ['Anos de Estudo', 'Frequencia']

print(tabela_frequencia_Anos_de_estudo)

                    Anos de Estudo  Frequencia
0                          11 anos        8718
1   Sem instrução e menos de 1 ano        3851
2                  15 anos ou mais        3590
3                           8 anos        3071
4                           4 anos        2628
5                           5 anos        1963
6                           3 anos        1521
7                           2 anos        1221
8                           7 anos        1150
9                           6 anos        1056
10                         10 anos         953
11                           1 ano         923
12                          9 anos         874
13                         12 anos         658
14                         14 anos         471
15                         13 anos         444
16                Não determinados          91

In [13]:
# ordenando a coluna idade em ordem crescente para sabem quem é a maior e a menor idade
df['Idade'].sort_values()

2798     13
22316    15
13158    15
19232    15
28607    15
         ..
8234     91
10899    92
26216    92
1789     95
11834    97
Name: Idade, Length: 33183, dtype: int64

In [14]:
import math

# b) Categorizar as variáveis quantitativas e criar uma nova variáveis com essas categorias.

# VARIÁVEL Idade

#cálculo do número de classes:

n = 76839
k = 1 + 3.3*math.log10(n)
k

17.122419623927737

In [15]:
amp_idade = df['Idade'].max() - df['Idade'].min()
amp_idade

84

In [16]:
# AMplitude de cada classe:
k = 17

AmplitudeDeClasse = amp_idade / k
AmplitudeDeClasse

4.9411764705882355

In [17]:


# definir os limites dos intervalos para categorizzação da variável idade:

bins = [13, 18, 23, 28, 33, 38, 43, 48, 53, 58, 63, 68, 73, 78, 83, 88]

In [18]:
# fazendo a coluna do intervalo de classe da idade.
df['Intervalo de Classe - Idade'] = pd.cut(df['Idade'], bins, right=False)
df

,UF,Sexo,Idade,Cor,Anos de Estudo,Renda,Altura,Intervalo de Classe - Idade
0,Rondônia,Masculino,23,Parda,11 anos,800.0,1.603.807.616,"[23, 28)"
1,Rondônia,Feminino,23,Branca,11 anos,1150.0,1.739.789.827,"[23, 28)"
2,Rondônia,Feminino,35,Parda,14 anos,880.0,1.760.443.822,"[33, 38)"
3,Rondônia,Masculino,46,Branca,5 anos,3500.0,1.783.157.945,"[43, 48)"
4,Rondônia,Feminino,47,Parda,8 anos,150.0,1.690.630.954,"[43, 48)"
...,...,...,...,...,...,...,...,...
33178,Minas Gerais,Masculino,60,Preta,11 anos,8000.0,1.649.400.782,"[58, 63)"
33179,Minas Gerais,Masculino,33,Parda,14 anos,2300.0,1.693.094.939,"[33, 38)"
33180,Minas Gerais,Feminino,31,Parda,11 anos,2000.0,1.849.360.141,"[28, 33)"
33181,Minas Gerais,Feminino,52,Branca,8 anos,4000.0,1.785.048.175,"[48, 53)"
33182,Minas Gerais,Masculino,36,Parda,Sem instrução e menos de 1 ano,NaN,NaN,"[33, 38)"

In [19]:
# VARIÁVEL Renda

#cálculo do número de classes:

n = 76839
k = 1 + 3.3*math.log10(n)
k

17.122419623927737

In [20]:
# ordenando a coluna renda em ordem crescente para sabem quem é a maior e a menor renda
df['Renda'].sort_values()

11504         0.0
2309          0.0
2310          0.0
28776         0.0
2312          0.0
           ...
20905     50000.0
11454     60000.0
32379    100000.0
28110    200000.0
33182         NaN
Name: Renda, Length: 33183, dtype: float64

In [21]:
amp_renda = df['Renda'].max() - df['Renda'].min()
amp_renda

200000.0

In [22]:
# AMplitude de cada classe:
k = 17

AmplitudeDeClasse = amp_renda / k
AmplitudeDeClasse

11764.70588235294

In [34]:
# definir os limites dos intervalos para categorizzação da variável renda:

limites_intervalos = [df['Renda'].min() + i * AmplitudeDeClasse for i in range(k + 1)]
limites_intervalos

[0.0,
 118568956.23529412,
 237137912.47058824,
 355706868.7058824,
 474275824.9411765,
 592844781.1764706,
 711413737.4117647,
 829982693.6470588,
 948551649.882353,
 1067120606.117647,
 1185689562.3529413,
 1304258518.5882354,
 1422827474.8235295,
 1541396431.0588236,
 1659965387.2941177,
 1778534343.5294118,
 1897103299.764706,
 2015672256.0]

In [35]:
df['Intervalo de Classe - Renda'] = pd.cut(df['Renda'], bins=limites_intervalos, right=False)
df

,UF,Sexo,Idade,Cor,Anos de Estudo,Renda,Altura,Intervalo de Classe - Idade,Faixa de Renda,Intervalo de Classe - Altura,Intervalo de Classe - Renda
0,Rondônia,Masculino,23,Parda,11 anos,800.0,1603807616,"[23, 28)","[0.0, 11764.706)","[1541553757.059, 1660122713.294)","[0.0, 118568956.235)"
1,Rondônia,Feminino,23,Branca,11 anos,1150.0,1739789827,"[23, 28)","[0.0, 11764.706)","[1660122713.294, 1778691669.529)","[0.0, 118568956.235)"
2,Rondônia,Feminino,35,Parda,14 anos,880.0,1760443822,"[33, 38)","[0.0, 11764.706)","[1660122713.294, 1778691669.529)","[0.0, 118568956.235)"
3,Rondônia,Masculino,46,Branca,5 anos,3500.0,1783157945,"[43, 48)","[0.0, 11764.706)","[1778691669.529, 1897260625.765)","[0.0, 118568956.235)"
4,Rondônia,Feminino,47,Parda,8 anos,150.0,1690630954,"[43, 48)","[0.0, 11764.706)","[1660122713.294, 1778691669.529)","[0.0, 118568956.235)"
...,...,...,...,...,...,...,...,...,...,...,...
33178,Minas Gerais,Masculino,60,Preta,11 anos,8000.0,1649400782,"[58, 63)","[0.0, 11764.706)","[1541553757.059, 1660122713.294)","[0.0, 118568956.235)"
33179,Minas Gerais,Masculino,33,Parda,14 anos,2300.0,1693094939,"[33, 38)","[0.0, 11764.706)","[1660122713.294, 1778691669.529)","[0.0, 118568956.235)"
33180,Minas Gerais,Feminino,31,Parda,11 anos,2000.0,1849360141,"[28, 33)","[0.0, 11764.706)","[1778691669.529, 1897260625.765)","[0.0, 118568956.235)"
33181,Minas Gerais,Feminino,52,Branca,8 anos,4000.0,1785048175,"[48, 53)","[0.0, 11764.706)","[1778691669.529, 1897260625.765)","[0.0, 118568956.235)"
33182,Minas Gerais,Masculino,36,Parda,Sem instrução e menos de 1 ano,NaN,<NA>,"[33, 38)",NaN,NaN,NaN

In [25]:
# VARIÁVEL Altura

#cálculo do número de classes:

n = 76839
k = 1 + 3.3*math.log10(n)
k

17.122419623927737

In [31]:
# ordenando a coluna Altura em ordem crescente para sabem quem é a maior e a menor altura
df['Altura'].sort_values()

8273         157326
28455        165652
19147        169133
818          179008
29505        179828
            ...
12688    1990396629
18398    1994329103
23062    2001359249
27248    2015829582
33182          <NA>
Name: Altura, Length: 33183, dtype: Int64

In [27]:
# Remover os pontos de separação de milhares e converter para números inteiros
df['Altura'] = df['Altura'].str.replace('.', '').astype(float).astype(pd.Int64Dtype())
print(df)

                 UF       Sexo  Idade     Cor                  Anos de Estudo  \
0          Rondônia  Masculino     23   Parda                         11 anos
1          Rondônia   Feminino     23  Branca                         11 anos
2          Rondônia   Feminino     35   Parda                         14 anos
3          Rondônia  Masculino     46  Branca                          5 anos
4          Rondônia   Feminino     47   Parda                          8 anos
...             ...        ...    ...     ...                             ...
33178  Minas Gerais  Masculino     60   Preta                         11 anos
33179  Minas Gerais  Masculino     33   Parda                         14 anos
33180  Minas Gerais   Feminino     31   Parda                         11 anos
33181  Minas Gerais   Feminino     52  Branca                          8 anos
33182  Minas Gerais  Masculino     36   Parda  Sem instrução e menos de 1 ano

        Renda      Altura Intervalo de Classe - Idade    Faixa de Renda
0       800.0  1603807616                    [23, 28)  [0.0, 11764.706)
1      1150.0  1739789827                    [23, 28)  [0.0, 11764.706)
2       880.0  1760443822                    [33, 38)  [0.0, 11764.706)
3      3500.0  1783157945                    [43, 48)  [0.0, 11764.706)
4       150.0  1690630954                    [43, 48)  [0.0, 11764.706)
...       ...         ...                         ...               ...
33178  8000.0  1649400782                    [58, 63)  [0.0, 11764.706)
33179  2300.0  1693094939                    [33, 38)  [0.0, 11764.706)
33180  2000.0  1849360141                    [28, 33)  [0.0, 11764.706)
33181  4000.0  1785048175                    [48, 53)  [0.0, 11764.706)
33182     NaN        <NA>                    [33, 38)               NaN

[33183 rows x 9 columns]

In [28]:
amp_altura = df['Altura'].max() - df['Altura'].min()
amp_altura

2015672256

In [29]:
# AMplitude de cada classe:
k = 17

AmplitudeDeClasse = amp_altura / k
AmplitudeDeClasse

118568956.23529412

In [30]:
# definir os limites dos intervalos para categorizzação da variável altura:

limites_intervalos = [df['Altura'].min() + i * AmplitudeDeClasse for i in range(k + 1)]
limites_intervalos

[157326.0,
 118726282.23529412,
 237295238.47058824,
 355864194.7058824,
 474433150.9411765,
 593002107.1764706,
 711571063.4117647,
 830140019.6470588,
 948708975.882353,
 1067277932.117647,
 1185846888.3529413,
 1304415844.5882354,
 1422984800.8235295,
 1541553757.0588236,
 1660122713.2941177,
 1778691669.5294118,
 1897260625.764706,
 2015829582.0]

In [32]:
df['Intervalo de Classe - Altura'] = pd.cut(df['Altura'], bins=limites_intervalos, right=False)
df

,UF,Sexo,Idade,Cor,Anos de Estudo,Renda,Altura,Intervalo de Classe - Idade,Faixa de Renda,Intervalo de Classe - Altura
0,Rondônia,Masculino,23,Parda,11 anos,800.0,1603807616,"[23, 28)","[0.0, 11764.706)","[1541553757.059, 1660122713.294)"
1,Rondônia,Feminino,23,Branca,11 anos,1150.0,1739789827,"[23, 28)","[0.0, 11764.706)","[1660122713.294, 1778691669.529)"
2,Rondônia,Feminino,35,Parda,14 anos,880.0,1760443822,"[33, 38)","[0.0, 11764.706)","[1660122713.294, 1778691669.529)"
3,Rondônia,Masculino,46,Branca,5 anos,3500.0,1783157945,"[43, 48)","[0.0, 11764.706)","[1778691669.529, 1897260625.765)"
4,Rondônia,Feminino,47,Parda,8 anos,150.0,1690630954,"[43, 48)","[0.0, 11764.706)","[1660122713.294, 1778691669.529)"
...,...,...,...,...,...,...,...,...,...,...
33178,Minas Gerais,Masculino,60,Preta,11 anos,8000.0,1649400782,"[58, 63)","[0.0, 11764.706)","[1541553757.059, 1660122713.294)"
33179,Minas Gerais,Masculino,33,Parda,14 anos,2300.0,1693094939,"[33, 38)","[0.0, 11764.706)","[1660122713.294, 1778691669.529)"
33180,Minas Gerais,Feminino,31,Parda,11 anos,2000.0,1849360141,"[28, 33)","[0.0, 11764.706)","[1778691669.529, 1897260625.765)"
33181,Minas Gerais,Feminino,52,Branca,8 anos,4000.0,1785048175,"[48, 53)","[0.0, 11764.706)","[1778691669.529, 1897260625.765)"
33182,Minas Gerais,Masculino,36,Parda,Sem instrução e menos de 1 ano,NaN,<NA>,"[33, 38)",NaN,NaN

c) Tabela de frequência para as novas variáveis categóricas

In [38]:
# * Tabela de Frequência para a variável Intervalo de Classe - Idade: *

tabela_frequencia_ic_idade = df['Intervalo de Classe - Idade'].value_counts().reset_index()
tabela_frequencia_ic_idade.columns = ['Intervalo de Classe - Idade', 'Frequencia']

print(tabela_frequencia_ic_idade)

   Intervalo de Classe - Idade  Frequencia
0                     [33, 38)        4761
1                     [38, 43)        4659
2                     [43, 48)        4416
3                     [48, 53)        4242
4                     [28, 33)        3781
5                     [53, 58)        3362
6                     [58, 63)        2290
7                     [23, 28)        2251
8                     [63, 68)        1353
9                     [18, 23)         837
10                    [68, 73)         648
11                    [73, 78)         334
12                    [78, 83)         145
13                    [83, 88)          46
14                    [13, 18)          36

In [39]:
# * Tabela de Frequência para a variável Intervalo de Classe - Renda: *

tabela_frequencia_ic_renda = df['Intervalo de Classe - Renda'].value_counts().reset_index()
tabela_frequencia_ic_renda.columns = ['Intervalo de Classe - Renda', 'Frequencia']

print(tabela_frequencia_ic_renda)

         Intervalo de Classe - Renda  Frequencia
0               [0.0, 118568956.235)       33182
1   [1067120606.118, 1185689562.353)           0
2   [1778534343.529, 1897103299.765)           0
3   [1659965387.294, 1778534343.529)           0
4   [1541396431.059, 1659965387.294)           0
5   [1422827474.824, 1541396431.059)           0
6   [1304258518.588, 1422827474.824)           0
7   [1185689562.353, 1304258518.588)           0
8    [948551649.882, 1067120606.118)           0
9     [118568956.235, 237137912.471)           0
10    [829982693.647, 948551649.882)           0
11    [711413737.412, 829982693.647)           0
12    [592844781.176, 711413737.412)           0
13    [474275824.941, 592844781.176)           0
14    [355706868.706, 474275824.941)           0
15    [237137912.471, 355706868.706)           0
16    [1897103299.765, 2015672256.0)           0

In [40]:
# * Tabela de Frequência para a variável Intervalo de Classe - Altura: *

tabela_frequencia_ic_altura = df['Intervalo de Classe - Altura'].value_counts().reset_index()
tabela_frequencia_ic_altura.columns = ['Intervalo de Classe - Altura', 'Frequencia']

print(tabela_frequencia_ic_altura)

        Intervalo de Classe - Altura  Frequencia
0   [1660122713.294, 1778691669.529)       15695
1   [1541553757.059, 1660122713.294)        8595
2   [1778691669.529, 1897260625.765)        4700
3     [118726282.235, 237295238.471)        2924
4   [1422984800.824, 1541553757.059)         710
5          [157326.0, 118726282.235)         347
6     [1897260625.765, 2015829582.0)         196
7   [1304415844.588, 1422984800.824)          14
8     [830140019.647, 948708975.882)           0
9     [711571063.412, 830140019.647)           0
10  [1067277932.118, 1185846888.353)           0
11  [1185846888.353, 1304415844.588)           0
12    [593002107.176, 711571063.412)           0
13    [474433150.941, 593002107.176)           0
14    [355864194.706, 474433150.941)           0
15    [237295238.471, 355864194.706)           0
16   [948708975.882, 1067277932.118)           0